### ISSUE TITLE
初期コンテンツ案

### ISSUE THREAD

**Issue by watilde** [aws-amplify-jp/aws-amplify-jp.github.io#1]
この辺を用意しようと思っています。
+ Who we are
+ Links to resources
+ Events

その他あればコメント頂けると嬉しいです！

**Comment by ikenyal** [comment]
- コミュニティ紹介
  - コミュニティの目的/趣旨
  - 運営体制（運営としての活動を公式に証明できる場所があると嬉しい）
  - 活動レポート
- リソース集
  - 学習リソースのリンク集
  - AWS導入企業・サービス（あのGitHubのリポジトリが活性化したら良いが、今の数だと・・・）
- イベント
  - イベント一覧(connpass APIベース)
  - 行動規範（毎回）
  - イベントレポート
  - フォト（オフラインイベントが再開したら）
- お問い合わせ

Slack上にも記載しましたが、育ったフェーズを見越したらこんな構造はどうでしょう？？

**Comment by tacck** [comment]
池田さんのにのっかる感じで。

オンラインでも登壇者の集合画面(Zoomの参加者一覧とか)のスクリーンショットを撮ったりする場合もあったりするので、
イベントの規約的なところで登壇者向けに「最後に集合写真撮ります」的なものもあると良さそうですね。

**Comment by togami2864** [comment]
些細なことですが、学習リソースへのリンク集に加えて、amplify jp slackや公式のdiscordなどコミュニティへのリンクもあったほうがいいと思います。

**Comment by watilde** [comment]
下記は、google docsなどで共同編集しながらv1を作成する
> コミュニティ紹介
>   コミュニティの目的/趣旨
>   運営体制（運営としての活動を公式に証明できる場所があると嬉しい）
>   活動レポート

**Comment by watilde** [comment]
Issue報告リンクをフッターかどこかに。

**Comment by watilde** [comment]
みなさんコメントありがとうございました！ここで出たアイデアを別チケットにて建てたので、closeします。また何か良いアイデアあれば、別途チケット作成を一緒にさせてください :)
