### ISSUE TITLE
CoCページにてフッターがライセンスのリンクにかぶってクリックできない

### ISSUE THREAD

**Issue by togami2864** [aws-amplify-jp/aws-amplify-jp.github.io#24]
## 内容
「この作品はCreative Commons Attribution 3.0 Unported Licenseでライセンスされています」という文言がフッターとかぶって見えにくい。  
また、Creative Commons Attribution 3.0 Unported Licenseへのリンクをクリックできない。

<img width="1267" alt="スクリーンショット 2021-07-13 23 35 51" src="https://user-images.githubusercontent.com/62130798/125471500-e4bd2772-a5e0-423f-8fd4-4a3edbe603f3.png">

**Comment by watilde** [comment]
ありがとうございます！こちら、localだと再現しないのでbuildファイルがうまく更新されていない可能性ありますね。 `gatsby clean` 以外にcacheを更新する方法を考えねば。

**Comment by watilde** [comment]
Refs: https://github.com/gatsbyjs/gatsby/issues/25994

**Comment by itomise** [comment]
こちら、フッターが画面全体に positino: fixed, bottom: 0 になっているのが原因かと思いますので、wrapperを用意してfooterの高さ分 padding-bottomするのが良いかと思っているのですがいかがでしょうか？

**Comment by watilde** [comment]
解決しました。起票ありがとうございます！
![Screen Shot 2021-07-14 at 12 43 09](https://user-images.githubusercontent.com/1716463/125557652-27bd411a-d3e3-44c4-8226-2584eeaba48a.png)
