### ISSUE TITLE
コントリビューターの一覧を表示 Ver.2

### ISSUE THREAD

**Issue by watilde** [aws-amplify-jp/aws-amplify-jp.github.io#56]
##### ユーザーストーリー
コントリビューター向けに、`aws-amplify`関連repositoryへの貢献の可視化を提供したい。これにより、貢献の可視化が可能となる。

##### 受け入れ基準
1. `/contributors`を開く
2. 各リポジトリと日本のコントリビューターの名前と画像が表示される
3. コントリビューターをクリックするとGitHubのユーザーページに飛ぶ

**Comment by fossamagna** [comment]
このissueに取り組んでみようと考えていて、`日本のコントリビューター`という部分の判断をどうやろうか検討しています。

GitHubのプロフィールの`Location`に日本の地名(`Tokyo`, `Japan`など)が含まれているユーザーを`日本のコントリビューター`として扱うという案を考えましたが、以下の2つの問題があります。
1. Locationの記述はフリーなのですべてのバリエーションを網羅できない。そもそも必須でもないので何も入力していないユーザーも存在する。
2. ユーザーの`Location`を取得するには`GET /users/{username}`のGitHub APIを呼び出す必要があり、APIの呼び出す数が膨大になる。対象リポジトリの全コントリビュータの数だけ呼び出すことになる。ビルド時間も長くなってしまう。ローカルでビルドする際にもトークンがないとRate Limitにかかってしまう。

1つ目の問題点に対しては`日本のコントリビューター`のリストを持つという方法で対応できるかと思います。その場合、2つ目の問題点の緩和にもなるかなと思います（ビルド時にGitHub APIの呼び出し数が減る）。ただ、この場合リストをいつどう更新するかがポイントになると考えています。
そこで、このリスト更新処理として定期的にGitHub Actionsで`日本のコントリビューター`のリストを更新（追記）してgit commit & pushしておくのはどうかなと考えています。この処理ではGitHub APIを使ってユーザーのLocationから日本と判断したコントリビュータをリストに追加します。こうすれば、時間がかかる処理は`npm start`, `npm run build`とは別に動くことにので（ローカル環境でもCIでも）ビルド時間も今までとそれほど変わらずに済むと思います。また、あくまでこの処理はでリストに追加しない想定です。`Location`で判断できないコントリビュータを手動でもリストに追加することを想定しているからです。

他にもこんな方法がいいのでは？みたいないみなさんのご意見を聞いてみたいです。
