### ISSUE TITLE
イベントカレンダーの作成

### ISSUE THREAD

**Issue by watilde** [aws-amplify-jp/aws-amplify-jp.github.io#7]
#### ユーザーストーリー
Amplifyコミュニティに興味がある開発者向けに、日本で開催されているイベントの一覧が見れるページを提供したい。これにより、現在募集中のAmplify関連のイベントを見つけることができる。

#### 受け入れ基準
1. `/events` を開く
2. 次回イベントのタイトル、日付、URLが分かる

#### 追記
当初のアイデアとしてconnpassのAPIを使う予定だったが、Amplify Japan User Group以外のコミュニティが主催であってもイベント一覧に登録できるようにしたい。イベントごとにmarkdownを書いて、結合のような仕組みづくりが必要そう。

**Comment by togami2864** [comment]
ちょっと相談なのですが、mdのtableで記述して表示したところ以下のような感じになりました↓  

  
<img width="1256" alt="スクリーンショット 2021-07-12 23 42 05" src="https://user-images.githubusercontent.com/62130798/125386631-914abc00-e3d7-11eb-84ca-68c73137fcb9.png">
テーブル間の区切りがわかりにくくなって全体的に見にくくなってしまいます。
cssでtbodyタグあたりをいじれば多少のカスタムはできると思うのですが、どうしましょうか？

**Comment by watilde** [comment]
@togami2864 コメントありがとうございます！一旦borderと `background-color: #fff` を入れるのがよいのかなと思います。理想形としては、下記のmaterial-uiのtableを反映する方法を考える、なのかなと思います。

https://material-ui.com/components/tables/


実装は下記の`font.css`を参考に、`table.css`を作成してthemeでimportする形でいかがでしょう？
https://github.com/aws-amplify-jp/aws-amplify-jp.github.io/blob/develop/src/styles/theme.js#L2
