### ISSUE TITLE
コミュニティ概要のコンテンツ作成

### ISSUE THREAD

**Issue by watilde** [aws-amplify-jp/aws-amplify-jp.github.io#8]
#### ユーザーストーリー
Amplify Japan User Groupに興味のある開発者として、コミュニティの詳細、目的、運営者情報を提供したい。これにより、コミュニティについて理解が進み、興味があれば参加することができる。

#### 受け入れ基準
1. `/` を開く
2. 日本語でコミュニティの紹介、目的、運営メンバーが書かれている

**Comment by tacck** [comment]
叩き台。

-----

<コミュニティ紹介>

Amplify 日本ユーザーグループ (Amplify Japan User Group) は、  AWS Amplify の利用者・開発者が主体となり、相互に AWS Amplify の利用・開発をサポートするために、主に日本国内で活動するグループです。

-----

<コミュニティの目的>

本コミュニティは AWS Amplify について、主に日本国内の利用者および(または)日本語によって、情報交換する目的で運営するものです。
AWS Amplify の利用方法、実運用含めた開発時の知見や課題、周辺技術との連携に関する疑問、といったことがざっくばらんにやりとりされています。

また、定期的にミートアップを開催し、より多くの人に情報を伝える活動も行っています。

-----

<運営メンバー>

* Aki Tsukada
* Daijiro Wachi
* Jaga
* Kento Ikeda
* Koya Kimura
* Masahiko Murakami
* Ryota Ito
* tacck
* Yoshiaki Togami

```
↑ ひとまず、Slack の運営部屋のメンバーを表示順に。
各自に表示名やリンクなどを確認して、アルファベット順にする。
```

**Comment by watilde** [comment]
@tacck たたき台ありがとうございます！ミーティング参加者に絞って運営者をリスト化しつつ、一旦そちらで進められればと思っていま :)
